# Generated by Django 5.0.1 on 2024-03-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nutri', '0004_remove_food_breakfast_remove_food_dinner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDetails',
            fields=[
                ('food_id', models.IntegerField(primary_key=True, serialize=False)),
                ('meal_type', models.CharField(max_length=20)),
                ('food_name', models.CharField(max_length=100)),
                ('calories', models.FloatField()),
                ('fats', models.FloatField()),
                ('proteins', models.FloatField()),
                ('carbohydrates', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='food',
            name='meal_type',
            field=models.CharField(max_length=100),
        ),
    ]
